import type { RepoPatch } from "@/contracts";

function titleFromRepoName(repoName: string) {
  return repoName
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function buildPackageJson(title: string) {
  return JSON.stringify(
    {
      name: title.toLowerCase().replace(/\s+/g, "-"),
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        next: "latest",
        react: "latest",
        "react-dom": "latest"
      },
      devDependencies: {
        "@types/node": "latest",
        "@types/react": "latest",
        "@types/react-dom": "latest",
        autoprefixer: "latest",
        postcss: "latest",
        tailwindcss: "latest",
        typescript: "latest"
      }
    },
    null,
    2
  );
}

function buildPageSource(title: string) {
  return `const bullets = [
  "Design with screenshots, voice, or text instructions",
  "Deploy fast on Vercel with a repo-ready starter",
  "Use this page as your first editable surface inside Vibex"
];

export default function HomePage() {
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(143,232,255,0.18),transparent_38%),#05070c] text-slate-50">
      <section className="mx-auto flex min-h-screen max-w-6xl flex-col justify-between px-6 py-10 sm:px-10 lg:px-12">
        <div className="flex items-center justify-between text-xs uppercase tracking-[0.32em] text-cyan-200/70">
          <span>Starter site</span>
          <span>${title}</span>
        </div>
        <div className="grid gap-14 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div className="max-w-2xl">
            <p className="mb-4 text-sm uppercase tracking-[0.3em] text-lime-200/80">
              Ready for Vibex
            </p>
            <h1 className="max-w-xl text-5xl font-semibold tracking-tight text-white sm:text-7xl">
              Start shaping ${title} in seconds.
            </h1>
            <p className="mt-6 max-w-lg text-base leading-7 text-slate-300 sm:text-lg">
              This repo is seeded with a minimal Next.js and Tailwind surface so you can start
              designing immediately from your phone.
            </p>
          </div>
          <div className="space-y-4">
            {bullets.map((bullet) => (
              <div
                key={bullet}
                className="border border-white/10 bg-white/[0.03] px-5 py-4 text-sm leading-6 text-slate-300 backdrop-blur"
              >
                {bullet}
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
`;
}

export function buildStarterSitePatch(repoName: string): RepoPatch {
  const title = titleFromRepoName(repoName) || "Starter Site";

  return {
    commitMessage: "Initialize Vibex starter site",
    summary: `Seed a minimal Next.js App Router starter for ${title}.`,
    files: [
      {
        path: "package.json",
        operation: "upsert",
        reason: "Create a lightweight Next.js and Tailwind starter workspace.",
        content: buildPackageJson(title)
      },
      {
        path: "tsconfig.json",
        operation: "upsert",
        reason: "Add a TypeScript config for the starter app.",
        content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
      },
      {
        path: "next-env.d.ts",
        operation: "upsert",
        reason: "Provide Next.js TypeScript environment declarations.",
        content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js.
`
      },
      {
        path: "next.config.ts",
        operation: "upsert",
        reason: "Enable a typed Next.js config file.",
        content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`
      },
      {
        path: "postcss.config.mjs",
        operation: "upsert",
        reason: "Configure Tailwind CSS processing.",
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
`
      },
      {
        path: "tailwind.config.ts",
        operation: "upsert",
        reason: "Set up Tailwind content scanning for the starter app.",
        content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {}
  },
  plugins: []
};

export default config;
`
      },
      {
        path: "app/layout.tsx",
        operation: "upsert",
        reason: "Create the App Router root layout.",
        content: `import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "${title}",
  description: "A Vibex starter site ready for real-time design changes."
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
      },
      {
        path: "app/page.tsx",
        operation: "upsert",
        reason: "Ship an initial landing page that is easy to iterate on.",
        content: buildPageSource(title)
      },
      {
        path: "app/globals.css",
        operation: "upsert",
        reason: "Add the Tailwind base layer and starter design tokens.",
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
  background: #05070c;
  color: #f4f7fb;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

a {
  color: inherit;
  text-decoration: none;
}
`
      },
      {
        path: "README.md",
        operation: "upsert",
        reason: "Explain how to run the seeded starter locally.",
        content: `# ${title}

This repository was initialized by Vibex with a minimal Next.js App Router and Tailwind starter.

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Connect the repository to Vercel when you are ready to preview live deployments.
`
      }
    ]
  };
}
